/**
 * Created by rahulkookal on 22/8/17.
 */
export const api = {
    "stories":[
        {
            "author-name":"Teresa Davenport",
            "headline":"5 Great Reasons to Visit Cuba & Things to Know Before Traveling",
            "slug":"international/2017/03/17/5-great-reasons-to-visit-cuba-and-things-to-know-before-traveling",
            "last-published-at":1495092430175,
            "alternative":{

            },
            "sections":[
                {
                    "id":99,
                    "name":"International",
                    "display-name":"International",
                    "slug":"international",
                    "parent-id":98,
                    "collection":null
                },
                {
                    "id":2990,
                    "name":"Travel",
                    "display-name":"Travel",
                    "slug":"travel",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":780,
                "height":439,
                "mime-type":"image/jpeg"
            },
            "published-at":1495092430175,
            "id":"17de2da2-01fd-47a0-ae46-35b184f47c61",
            "hero-image-s3-key":"quintype-demo/2015-11/21006f30-9d7e-4219-ba96-4b2fd945e53c/cuba14.jpg",
            "author-id":5450,
            "first-published-at":1489733540858,
            "story-template":"listicle",
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"5 Times Joey was more thoughtful than his other friends",
            "slug":"culture/2016/04/07/5-Times-Joey-was-more-thoughtful-than-his-other-friends",
            "last-published-at":1501844379444,
            "alternative":{

            },
            "sections":[
                {
                    "id":142,
                    "name":"Culture",
                    "display-name":null,
                    "slug":"culture",
                    "parent-id":null,
                    "collection":{
                        "id":6626,
                        "name":"motherly",
                        "slug":"motherly"
                    }
                }
            ],
            "hero-image-metadata":{
                "width":2560,
                "height":1536,
                "mime-type":"image/jpeg"
            },
            "published-at":1501844379444,
            "id":"2e30cea1-b063-4531-9cbd-4f8631e55f60",
            "hero-image-s3-key":"quintype-demo/2016-04/313c85cc-b6c9-4825-9a61-6421e959fd1f/Friends-season-10-014.jpg",
            "author-id":2041,
            "first-published-at":1460029776973,
            "story-template":"listicle",
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"My next vacation - Dubai !",
            "slug":"culture/2017/05/22/My-next-vacation-Dubai",
            "last-published-at":1496042245681,
            "alternative":{

            },
            "sections":[
                {
                    "id":142,
                    "name":"Culture",
                    "display-name":null,
                    "slug":"culture",
                    "parent-id":null,
                    "collection":{
                        "id":6626,
                        "name":"motherly",
                        "slug":"motherly"
                    }
                }
            ],
            "hero-image-metadata":{
                "width":930,
                "height":581
            },
            "published-at":1496042245681,
            "id":"9eaf7b8f-7ad9-4f2b-ae8d-b9c2b652a3a7",
            "hero-image-s3-key":"quintype-demo/2017-04/802d7ef1-6043-4f7e-84d3-fc9f556d5097/G-1.jpg",
            "author-id":2041,
            "first-published-at":1495459792871,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"The Greatest !",
            "slug":"sports/2016/06/08/the-greatest",
            "last-published-at":1490835544186,
            "alternative":{

            },
            "sections":[
                {
                    "id":82,
                    "name":"Sports",
                    "display-name":"Sports",
                    "slug":"sports",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":2133,
                "height":1906,
                "focus-point":[
                    988,
                    258
                ]
            },
            "published-at":1490835544186,
            "id":"1d2fc836-4113-4ae1-8735-377167664892",
            "hero-image-s3-key":"quintype-demo/2016-06/cca8f31e-9264-4ee2-9af0-08eb53be2a26/ABP-1.jpg",
            "author-id":2041,
            "first-published-at":1465407509866,
            "story-template":"photo",
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"The 8th Win ....",
            "slug":"sports/2017/07/17/The-8th-Win",
            "last-published-at":1500533537708,
            "alternative":{

            },
            "sections":[
                {
                    "id":82,
                    "name":"Sports",
                    "display-name":"Sports",
                    "slug":"sports",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":960,
                "height":540,
                "focus-point":[
                    494,
                    177
                ]
            },
            "published-at":1500533537708,
            "id":"074b5b55-99fa-4cf1-a05d-b9751a03b4a4",
            "hero-image-s3-key":"quintype-demo/2017-07/e4bac9eb-6c32-4f07-a16a-90fa40166c35/DH-1.jpeg",
            "author-id":2041,
            "first-published-at":1500289049983,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Sriram Krishnaswamy",
            "headline":"Jeep Compass Launched in India, Prices Start at Rs 14.95 Lakh!  \u00A0",
            "slug":"travel/2017/08/03/jeep-compass-review",
            "last-published-at":1501758903636,
            "alternative":{

            },
            "sections":[
                {
                    "id":2990,
                    "name":"Travel",
                    "display-name":"Travel",
                    "slug":"travel",
                    "parent-id":null,
                    "collection":null
                },
                {
                    "id":84,
                    "name":"Technology",
                    "display-name":null,
                    "slug":"technology",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":630,
                "height":354,
                "mime-type":"image/jpeg",
                "focus-point":[
                    280,
                    119
                ]
            },
            "published-at":1501758903636,
            "id":"f149e702-8f5f-45ff-af8d-6723de244ea6",
            "hero-image-s3-key":"quintype-demo/2016-12/18f81a4d-2ca6-4be8-86c2-782774b149d6/538fc6f3-1a4d-4cdb-8f08-e2a6cb5f4f71.jpg",
            "author-id":61657,
            "first-published-at":1501758903636,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Sheikh Mohammad\u2019s dream project",
            "slug":"cities/2017/06/07/Sheikh-Mohammads-dream-project",
            "last-published-at":1496834081906,
            "alternative":{

            },
            "sections":[
                {
                    "id":215,
                    "name":"Cities",
                    "display-name":"Metros",
                    "slug":"cities",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":900,
                "height":517
            },
            "published-at":1496834081906,
            "id":"35159e54-9100-4ee8-9d17-ac7d3b04e242",
            "hero-image-s3-key":"quintype-demo/2017-05/93dee75e-948e-4a6b-a650-aacd3a505ca8/JC-1.jpg",
            "author-id":2041,
            "first-published-at":1496834081906,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Dhola Sadiya Bridge\u00A0",
            "slug":"current-affairs/2017/05/29/Dhola-Sadiya-Bridge",
            "last-published-at":1496050663951,
            "alternative":{

            },
            "sections":[
                {
                    "id":98,
                    "name":"Current Affairs",
                    "display-name":null,
                    "slug":"current-affairs",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":675,
                "height":372
            },
            "published-at":1496050663951,
            "id":"db443e57-278a-4ba6-a94d-fe95d32ca55d",
            "hero-image-s3-key":"quintype-demo/2017-05/aae70123-b2e4-4061-8594-a61d9fc943e5/EN-1.jpg",
            "author-id":2041,
            "first-published-at":1496050663951,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Restart your Career",
            "slug":"current-affairs/2017/04/06/restart-your-career",
            "last-published-at":1491476706862,
            "alternative":{

            },
            "sections":[
                {
                    "id":98,
                    "name":"Current Affairs",
                    "display-name":null,
                    "slug":"current-affairs",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":417,
                "height":250
            },
            "published-at":1491476706862,
            "id":"acab7476-b83c-4a4b-a555-34c7ff677975",
            "hero-image-s3-key":"quintype-demo/2017-04/3404a951-dc0f-4092-b6c5-6d679c7427a0/VH-1.jpg",
            "author-id":2041,
            "first-published-at":1491476400291,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Big Cats in India ",
            "slug":"entertainment/2017/04/11/Big-Cats-in-India",
            "last-published-at":1491907785450,
            "alternative":{

            },
            "sections":[
                {
                    "id":81,
                    "name":"Entertainment",
                    "display-name":"Entertainment",
                    "slug":"entertainment",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":300,
                "height":168
            },
            "published-at":1491907785450,
            "id":"dfb8b1fc-7632-4160-88d5-3adfc9c29a39",
            "hero-image-s3-key":"quintype-demo/2017-03/67553988-7334-404a-9214-eefbe9c654c9/IPS-1.jpeg",
            "author-id":2041,
            "first-published-at":1491907785450,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Andamans - your next holiday",
            "slug":"entertainment/2017/02/20/Andamans-your-next-holiday",
            "last-published-at":1487581299594,
            "alternative":{

            },
            "sections":[
                {
                    "id":81,
                    "name":"Entertainment",
                    "display-name":"Entertainment",
                    "slug":"entertainment",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":802,
                "height":615,
                "focus-point":[
                    369,
                    321
                ]
            },
            "published-at":1487581299594,
            "id":"b306aeb6-0411-4811-a516-bdf17b67c8d8",
            "hero-image-s3-key":"quintype-demo/2017-02/12f2e4e3-d228-43a4-aedf-d1eaad2e9faa/LHI-1.jpg",
            "author-id":2041,
            "first-published-at":1487579504383,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Abhinav Bindra narrowly misses a medal",
            "slug":"sports/2016/08/09/abhinav-bindra-narrowly-misses-a-medal",
            "last-published-at":1489732642219,
            "alternative":{

            },
            "sections":[
                {
                    "id":82,
                    "name":"Sports",
                    "display-name":"Sports",
                    "slug":"sports",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":318,
                "height":159
            },
            "published-at":1489732642219,
            "id":"6bc5bd62-0073-45cc-849f-217758e0984e",
            "hero-image-s3-key":"quintype-demo/2016-08/d17e1618-dfd4-44ef-9f12-00690cf1f131/T-1.jpeg",
            "author-id":2041,
            "first-published-at":1470723365685,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Understanding the Black Economy",
            "slug":"current-affairs/2017/03/19/Understanding-the-Black-Economy",
            "last-published-at":1490160250104,
            "alternative":{

            },
            "sections":[
                {
                    "id":98,
                    "name":"Current Affairs",
                    "display-name":null,
                    "slug":"current-affairs",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":444,
                "height":435,
                "focus-point":[
                    247,
                    147
                ]
            },
            "published-at":1490160250104,
            "id":"ee9bb3f9-2cfe-4df1-ac52-6f2a5fac6f97",
            "hero-image-s3-key":"quintype-demo/2017-03/7e436c34-e6b6-4c5f-a7b6-06b5172970be/NL-2.jpg",
            "author-id":2041,
            "first-published-at":1489914116611,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Sriram Krishnaswamy",
            "headline":"A Simple Guide to a Peaceful Life  \u00A0",
            "slug":"travel/2017/05/18/peaceful-life",
            "last-published-at":1495128532491,
            "alternative":{

            },
            "sections":[
                {
                    "id":2990,
                    "name":"Travel",
                    "display-name":"Travel",
                    "slug":"travel",
                    "parent-id":null,
                    "collection":null
                },
                {
                    "id":142,
                    "name":"Culture",
                    "display-name":null,
                    "slug":"culture",
                    "parent-id":null,
                    "collection":{
                        "id":6626,
                        "name":"motherly",
                        "slug":"motherly"
                    }
                }
            ],
            "hero-image-metadata":{
                "width":759,
                "height":422,
                "focus-point":[
                    252,
                    107
                ]
            },
            "published-at":1495128532491,
            "id":"12b82ae7-560f-4373-b3bd-439a79da3559",
            "hero-image-s3-key":"quintype-demo/2015-10/583ff746-cf97-45f8-8372-211e6b312acb/DJ-6.jpg",
            "author-id":61657,
            "first-published-at":1495128532491,
            "story-template":null,
            "metadata":{
                "story-attributes":{
                    "week":[

                    ]
                },
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"When is Tesla entering the Indian market?",
            "slug":"technology/2017/02/23/When-is-Tesla-entering-the-Indian-market",
            "last-published-at":1487840302541,
            "alternative":{

            },
            "sections":[
                {
                    "id":84,
                    "name":"Technology",
                    "display-name":null,
                    "slug":"technology",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":650,
                "height":308
            },
            "published-at":1487840302541,
            "id":"b9694979-8fb2-44f7-b8d7-b1d6efedfa6a",
            "hero-image-s3-key":"quintype-demo/2017-02/d916f4a6-3a0b-4c3f-803e-97793417587c/D-1.jpeg",
            "author-id":2041,
            "first-published-at":1487840302541,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Sriram Krishnaswamy",
            "headline":"I know what it\u2019s like to spend school holidays hungry",
            "slug":"entertainment/2017/07/27/kids-story-series",
            "last-published-at":1501151440523,
            "alternative":{

            },
            "sections":[
                {
                    "id":81,
                    "name":"Entertainment",
                    "display-name":"Entertainment",
                    "slug":"entertainment",
                    "parent-id":null,
                    "collection":null
                },
                {
                    "id":2990,
                    "name":"Travel",
                    "display-name":"Travel",
                    "slug":"travel",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":259,
                "height":194,
                "focus-point":[
                    169,
                    97
                ]
            },
            "published-at":1501151440523,
            "id":"813545ce-2907-4c45-b222-85a8000f0b71",
            "hero-image-s3-key":"quintype-demo/2015-10/0814a279-d4aa-4dae-984d-bd607f7f7ced/DJ-5.jpeg",
            "author-id":61657,
            "first-published-at":1501151440523,
            "story-template":null,
            "metadata":{
                "story-attributes":{
                    "week":[
                        "4",
                        "6"
                    ]
                },
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"In the battle of perception, Kejriwal won this round",
            "slug":"politics/2017/07/20/in-the-battle-of-perception-kejriwal-won-this-round",
            "last-published-at":1500522632130,
            "alternative":null,
            "sections":[
                {
                    "id":83,
                    "name":"Politics",
                    "display-name":null,
                    "slug":"politics",
                    "parent-id":null,
                    "collection":{
                        "id":4364,
                        "name":"The Quint",
                        "slug":"the-quint"
                    }
                }
            ],
            "hero-image-metadata":{
                "width":380,
                "height":285,
                "mime-type":"image/jpeg"
            },
            "published-at":1500522632130,
            "id":"3e112b40-cc06-4d70-901b-f825bd92099e",
            "hero-image-s3-key":"quintype-demo/2015-12/a7098e1a-62f9-42fd-ac12-a97e49dacce7/FP-1.jpg",
            "author-id":2041,
            "first-published-at":1500522632130,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Chirdeep Shetty",
            "headline":"India vs China Battle",
            "slug":"politics/2017/07/09/India-vs-China-Battle",
            "last-published-at":1499594657010,
            "alternative":{

            },
            "sections":[
                {
                    "id":83,
                    "name":"Politics",
                    "display-name":null,
                    "slug":"politics",
                    "parent-id":null,
                    "collection":{
                        "id":4364,
                        "name":"The Quint",
                        "slug":"the-quint"
                    }
                }
            ],
            "hero-image-metadata":{
                "width":275,
                "height":183,
                "focus-point":[
                    196,
                    59
                ]
            },
            "published-at":1499594657010,
            "id":"7e803bcc-cb40-4f4d-b810-ae9ace8ba4c1",
            "hero-image-s3-key":"quintype-demo/2016-01/2d00bde7-a28c-4415-9382-9a9c6fb3c7fc/IPSMF-1.jpeg",
            "author-id":15338,
            "first-published-at":1499594657010,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"8 times Osama almost got captured",
            "slug":"politics/2017/07/06/8-times-Osama-almost-got-captured",
            "last-published-at":1499338400907,
            "alternative":{

            },
            "sections":[
                {
                    "id":83,
                    "name":"Politics",
                    "display-name":null,
                    "slug":"politics",
                    "parent-id":null,
                    "collection":{
                        "id":4364,
                        "name":"The Quint",
                        "slug":"the-quint"
                    }
                }
            ],
            "hero-image-metadata":{
                "width":275,
                "height":183,
                "mime-type":"image/jpeg"
            },
            "published-at":1499338400907,
            "id":"903dd527-2595-4566-9c50-df2880cf18b5",
            "hero-image-s3-key":"quintype-demo/2016-01/8bce31a0-af65-41e5-8ddc-059294ad6892/SL-3.jpeg",
            "author-id":2041,
            "first-published-at":1499338400907,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        },
        {
            "author-name":"Tapan Bhat",
            "headline":"Civic Issues",
            "slug":"current-affairs/2017/06/30/civic-issues",
            "last-published-at":1498802890706,
            "alternative":{

            },
            "sections":[
                {
                    "id":98,
                    "name":"Current Affairs",
                    "display-name":null,
                    "slug":"current-affairs",
                    "parent-id":null,
                    "collection":null
                }
            ],
            "hero-image-metadata":{
                "width":960,
                "height":540,
                "focus-point":[
                    323,
                    257
                ]
            },
            "published-at":1498802890706,
            "id":"673893c2-6dc3-4dc6-81fe-015498a28b54",
            "hero-image-s3-key":"quintype-demo/2017-06/53aee421-99c9-4f04-8ead-53e53f9c6e11/DH-1.jpg",
            "author-id":2041,
            "first-published-at":1498802139269,
            "story-template":null,
            "metadata":{
                "card-share":{
                    "shareable":true
                }
            }
        }
    ]
}